### ISSUE TITLE
Temas dos seminários

### ISSUE THREAD

**Issue by iagoac** [iagoac/dce692#2]
Abaixo estão os temas dos seminários e as datas (o número da aula) que eles deverão ser apresentados.  
Como temos 20 alunos nesta disciplina, cada seminário será realizado por um grupo de 2 ou 3 pessoas.  

Minha ideia é uma apresentação de 30 a 40 minutos que poderá ser síncrona (no horário da aula) ou assíncrona (com o upload de um vídeo no YouTube), sendo esta uma opção individual de cada grupo. Caso a opção assíncrona seja escolhida, o _link_ do vídeo deverá ser enviado até o horário da aula correspondente.

1. ~~Programação inteira (aula 24)~~
2. ~~Programação não-linear (aula 24)~~
3. ~~Heurísticas e meta-heurísticas (busca local) (aula 25)~~
4. ~~Heurísticas e meta-heurísticas (algoritmos evolucionários) (aula 25)~~
5. ~~Otimização multi-objetivo (aula 28)~~
6. ~~Análise Envoltória de Dados (DEA) (aula 28)~~
7. ~~Teoria dos Jogos (aula 28)~~
8. ~~Otimização sob incerteza (robusta, dinâmica e estocástica) (aula 28)~~

Comentem abaixo o nome do grupo de vocês e qual seminário vocês escolheram. O primeiro comentário que escolher um tema, leva!

**Comment by marcusmigueell** [comment]
Guilherme, Marcus e Patrick
Tema: Teoria dos jogos

Em sex, 27 de ago de 2021 18:28, Iago Augusto de Carvalho <
***@***.***> escreveu:

**Comment by FairKillerMan** [comment]
Thiago Silva e Gustavo Lima
Tema: Análise Envoltória de Dados (DEA)

**Comment by brmgf** [comment]
Milene, Alice e Kleyton
Tema: Programação não-linear

**Comment by LuanBuenoBastos** [comment]
Grupo: Luan Bueno e Wesley Velloso Marques.

Tema: Programação inteira.

**Comment by HelbertSousa** [comment]
- Grupo:  💻 
 Helbert 
 Pedro
 Flaviane

- Tema: 📚 
 Heurísticas e meta-heurísticas (algoritmos evolucionários) (aula 25)

**Comment by nataliam002** [comment]
Natália Machado

Heurísticas e meta-heurísticas (busca local) (aula 25)

**Comment by JoaoHugo** [comment]
Grupo: João Hugo Marinho e Maximiano Cid Neto

Tema: Otimização multi-objetivo (aula 26)

**Comment by viniciusddmoreira** [comment]
Grupo: Vitor Risso Parisi, Iago Vinicius Siqueira Ribeiro e Vinícius Daniel D. Moreira
Tema: Otimização sob incerteza (robusta, dinâmica e estocástica) (aula 28)
