### ISSUE TITLE
Gabarito da Lista 04

### ISSUE THREAD

**Issue by LuanBuenoBastos** [iagoac/dce692#4]
Notei que alguns erros de digitação produziram respostas equivocadas. 

**Exercício 1**

Trecho da solução apresentada : "Caminho de 9 para 5: < 9,8,1,5 >; Custo = 45"

Solução encontrada por mim ao executar o algoritmo de Dijkstra: Caminho de 9 para 5: < 9,2,4,5 >; Custo = 35

**Exercício 2**

Ao ordenar as arestas pelo peso, um erro de digitação colocou a aresta (B, C) na segunda posição com peso = 13. E como consequência, o peso da árvore encontrada foi de valor 69.

Visualizando o grafo apresentado, é possível perceber que o peso da aresta (B, C) é 25. Sendo assim, a aresta (B, C) ocupa a nona posição da lista de arestas ordenadas, isto de acordo com a ordenação que realizei (passível de erros). O peso da árvore que calculei é formada pelas arestas: (A, B), (A, E), (B, G), (E, F) e (E, C) com o valor de peso total 71.

**Comment by iagoac** [comment]
@LuanBuenoBastos você tem razão.  
Acabo de corrigir o gabarito e subir as respostas atualizadas
